### ISSUE TITLE
Footprint for VL53L0X?

### ISSUE THREAD

**Issue by LukeL99** [adafruit/Adafruit-VL53L0X-ToF-Distance-Sensor-PCB#1]
I'm implementing a custom design using the VL53L0X, and I can't find a footprint to use for it. I checked your design, and saw it was referenced from the microbuilder library, but I can't find it in the version of the microbuilder library I found online, nor in the Adafruit eagle library. Can you provide the part definition files somewhere?

Thanks!

**Comment by ladyada** [comment]
try http://slopjong.de/2012/12/06/eagle-extract-a-symbol-from-a-project-to-a-library/ !

**Comment by LukeL99** [comment]
Didn't know you could do that - worked great. Thanks for the fast response!

For anyone trying to do this in the future, open the schematic, and navigate to:

File > Export > Libraries

The ULP will only give you the footprint or the symbol, depending on whether you're on schematic or layout. Exporting will give you the full libraries.
