### ISSUE TITLE
Typo in the reference to product page.

### ISSUE THREAD

**Issue by AlvaroHermida** [adafruit/Adafruit-VL53L0X-ToF-Distance-Sensor-PCB#2]
The reference should be:
https://www.adafruit.com/product/3317
instead of the current:
https://www.adafruit.com/product/3177

**Comment by ladyada** [comment]
@hoffmannjan check it!

**Comment by hoffmannjan** [comment]
https://github.com/adafruit/Adafruit-VL53L0X-ToF-Distance-Sensor-PCB/pull/4

added readme + image + requested URL fix + license, please close when merged

**Comment by ladyada** [comment]
we cleaned this repo :)
